### ISSUE TITLE
Migrate the .Net Client to Netstandard

### ISSUE THREAD

**Issue by rinkeb** [SenseNet/sn-client-dotnet#11]
Hi there,

Do you have any plans to migrate the sn client to netstandard? 

I noticed the steps being taken to migrate the server components. I guess that especially makes sense for the client as it is intended to be incorporated as a component in other applications.

**Comment by tusmester** [comment]
Sure, it will happen soon, the Client library does not have any special dependencies and does not use Windows-specific APIs, so it should be straightforward. We'll publish a blog post about moving our projects to netstandard in one or two days.
