### ISSUE TITLE
GetCurrentUser cannot recognize the user

### ISSUE THREAD

**Issue by kavics** [SenseNet/sn-client-dotnet#131]
**Problem**: The current user is parsed from the JWT token's top-level property Subject as the userId. In some environments (e.g. integration test) the JWT does not contain this property.
**Solution**: Parse the Payload.client_sub property that is the user name in the following format: "builtin\admin" and load the user by this data.

For further information please check the comments below.

See jwt token in this line in the Repository.cs: https://github.com/SenseNet/sn-client-dotnet/blob/d1218c198451ac9850897592dff911c1dedafd5f/src/SenseNet.Client/Repository/Repository.cs#L586
``` csharp
var jwtSecurityToken = handler.ReadJwtToken(accessToken);
```

**Comment by hashtagnulla** [comment]
Partially resolved: when the claim "sub" is missing, we log the rest of the available claims in a warning entry. 

Strongly recommended to check the logs sometimes.
