### ISSUE TITLE
Query Custom ListFields

### ISSUE THREAD

**Issue by pietervanh** [SenseNet/sn-client-dotnet#2]
+TypeIs:CustomContract +#ContractDeadline:<'2011-09-01 12:00:00'

Execute above contentquery with Content.QueryAsync

            var results = await Content.QueryAsync("+TypeIs:CustomContract +#ContractDeadline:<'2011-09-01 12:00:00''",
                select: new[] { "Id", "Name", "Path", "Type", "DisplayName" },
                expand: new[] { "ModifiedBy" },
                settings: new QuerySettings
                {
                    EnableAutofilters = FilterStatus.Enabled,
                    Top = 2000
                });

'# fields' don't seem to be queryable

**Comment by diablosteve** [comment]
There is a problems with this example. There are 2 single quote ( ' ) at the end of the query. Using only one works for me.
Is there any other condition for this bug?
