### ISSUE TITLE
Error when using Content.UploadAsync to upload file with chinese file name

### ISSUE THREAD

**Issue by frankyuan** [SenseNet/sn-client-dotnet#5]
I'm trying to upload file with Chinese file name to sensenet using Content.UploadAsync. For some file names, such as 运维管理.txt , there is an exception "Specified value has invalid Control characters. Parameter name: value". If rename to another file name, maybe it works well. Seems like encode issue. Could you give me some suggestions?

I'm trying to upload file with Chinese file name to sensenet using Content.UploadAsync. For some file names, such as 运维管理.txt , there is an exception "Specified value has invalid Control characters. Parameter name: value". If rename to another file name, maybe it works well. Seems like encode issue. Could you give me some suggestions?

My code:

using (var stream = new FileStream(localFilePath, FileMode.Open))
{
    await Content.UploadAsync(parentPath, fileName, stream, "File");
}
StackTrace:

at System.Net.WebHeaderCollection.CheckBadChars(String name, Boolean isHeaderValue)  
at System.Net.WebHeaderCollection.Add(String name, String value)
at SenseNet.Client.RESTCaller.CreateChunkUploadWebRequest(String url, ServerContext server, UploadData uploadData, String boundary, Stream& requestStream) in sn-client-dotnet-master\sn-client-dotnet-master\src\SenseNet.Client\RESTCaller.cs:line 620
   at SenseNet.Client.RESTCaller.<UploadInternalAsync>d__23.MoveNext() in sn-client-dotnet-master\sn-client-dotnet-master\src\SenseNet.Client\RESTCaller.cs:line 490

**Comment by tusmester** [comment]
(We should update the [original SO question](http://stackoverflow.com/questions/43653968/error-when-using-content-uploadasync-to-upload-file-with-chinese-file-name) when this is solved.)

It is possible that we should handle this on **both client and server side** (meaning a modification should be made in the main [sensenet repo](https://github.com/SenseNet/sensenet) too), to make the server (_UploadAction_) understand both the _filename_ and _filename*_. properties of the _Content-Disposition_ header.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition

**Comment by tusmester** [comment]
Thank you @frankyuan and @drwatson1 for your patience, we [released](https://github.com/SenseNet/sn-client-dotnet/releases) the fix in v1.1.1.
