### ISSUE TITLE
Strongly typed client models

### ISSUE THREAD

**Issue by tusmester** [SenseNet/sn-client-dotnet#73]
Scenario: get content from sensenet and convert it to a model and pass it on to the client.

This issue is about providing **best practices** and possibly a **reusable code or client API** for converting general **dynamic content objects** into custom models that can be used by the business logic or passed down to the client of an Asp.Net app.

- can we automatize type conversion?
- what about different content types (schemas)?
- what about field types, for example reference fields?

**Comment by HegyiOliver** [comment]
A sample class that can convert dynamic content types into child classes. It can handle simple fields and defined models so far.

```
 public BaseSNModel(dynamic objectWithSamePropNames)
        {
            foreach (PropertyInfo prop in GetType().GetProperties())
            {
                try
                {
                    GetType().GetProperty(prop.Name)?.SetValue(this, objectWithSamePropNames[prop.Name].ToString());
                }
                catch (Exception)
                {
    
                        var typeName = String.Concat(GetType().Namespace,".", prop.Name);
                        var type = Type.GetType(typeName);
                        var refField = Activator.CreateInstance(type, objectWithSamePropNames[prop.Name]);
                        GetType().GetProperty(prop.Name)?.SetValue(this, refField);
                 }
            }
       }
                 
```
